### ISSUE TITLE
Change port run Arquillian

### ISSUE THREAD

**Issue by clpCoder** [kumuluz/kumuluzee-testing#6]
Hello
I am using Arquillian and KumuluzEE, which runs on port 8080, I changed the .yml file to another port but while running the tests I get the message "connection refused".
```

kumuluzee:
  name: ms-gen-uuid
  env:
    name: ms-gen-uuid
  version: 1.0.0
  server:
    base-url: http://localhost:7980/v1/
    http:
      port: 7980
```

Also try the arquillian.xml file with javaArguments -Dserver.port property, but it doesn't work, can someone help me with this problem, is it possible to run it on another port?
```

<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://jboss.org/schema/arquillian http://www.jboss.org/schema/arquillian/arquillian_1_0.xsd">
    <container qualifier="KumuluzEE" default="true">
        <configuration>
            <property name="includeRequiredLibraries">fromPom</property>
        </configuration>
    </container>

</arquillian>
```
